set(_CATKIN_CURRENT_PACKAGE "dsrc")
set(dsrc_VERSION "0.0.0")
set(dsrc_MAINTAINER "augustojv <augustojv@todo.todo>")
set(dsrc_PACKAGE_FORMAT "2")
set(dsrc_BUILD_DEPENDS "roscpp")
set(dsrc_BUILD_EXPORT_DEPENDS "roscpp")
set(dsrc_BUILDTOOL_DEPENDS "catkin")
set(dsrc_BUILDTOOL_EXPORT_DEPENDS )
set(dsrc_EXEC_DEPENDS "roscpp")
set(dsrc_RUN_DEPENDS "roscpp")
set(dsrc_TEST_DEPENDS )
set(dsrc_DOC_DEPENDS )
set(dsrc_URL_WEBSITE "")
set(dsrc_URL_BUGTRACKER "")
set(dsrc_URL_REPOSITORY "")
set(dsrc_DEPRECATED "")