// Generated by gencpp from file era_gazebo/ERAMsg.msg
// DO NOT EDIT!


#ifndef ERA_GAZEBO_MESSAGE_ERAMSG_H
#define ERA_GAZEBO_MESSAGE_ERAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <nav_msgs/OccupancyGrid.h>

namespace era_gazebo
{
template <class ContainerAllocator>
struct ERAMsg_
{
  typedef ERAMsg_<ContainerAllocator> Type;

  ERAMsg_()
    : header()
    , ID()
    , pose()
    , grid()  {
    }
  ERAMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ID(_alloc)
    , pose(_alloc)
    , grid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ID_type;
  _ID_type ID;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _grid_type;
  _grid_type grid;





  typedef boost::shared_ptr< ::era_gazebo::ERAMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::era_gazebo::ERAMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ERAMsg_

typedef ::era_gazebo::ERAMsg_<std::allocator<void> > ERAMsg;

typedef boost::shared_ptr< ::era_gazebo::ERAMsg > ERAMsgPtr;
typedef boost::shared_ptr< ::era_gazebo::ERAMsg const> ERAMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::era_gazebo::ERAMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::era_gazebo::ERAMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace era_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'era_gazebo': ['/home/nuc/catkin_ws/src/era_gazebo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::era_gazebo::ERAMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::era_gazebo::ERAMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::era_gazebo::ERAMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::era_gazebo::ERAMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::era_gazebo::ERAMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::era_gazebo::ERAMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::era_gazebo::ERAMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b95f2c9c8a23e957a60f31cf6a105519";
  }

  static const char* value(const ::era_gazebo::ERAMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb95f2c9c8a23e957ULL;
  static const uint64_t static_value2 = 0xa60f31cf6a105519ULL;
};

template<class ContainerAllocator>
struct DataType< ::era_gazebo::ERAMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "era_gazebo/ERAMsg";
  }

  static const char* value(const ::era_gazebo::ERAMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::era_gazebo::ERAMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
string ID\n\
geometry_msgs/Pose pose\n\
nav_msgs/OccupancyGrid grid\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
";
  }

  static const char* value(const ::era_gazebo::ERAMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::era_gazebo::ERAMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ID);
      stream.next(m.pose);
      stream.next(m.grid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ERAMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::era_gazebo::ERAMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::era_gazebo::ERAMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ID);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "grid: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.grid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERA_GAZEBO_MESSAGE_ERAMSG_H
